version: "3.8"

services:
  backend:
    build: ./backend
    container_name: f1-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: f1-frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend/static:/usr/share/nginx/html
    restart: unless-stopped
    depends_on:
      - backend

  mongo:
    image: mongo
    container_name: f1-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: {}
